### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

#### Вариант 1.  Создаю дословно по условию: "от числа N до 0"

In [1]:
import numpy as np

In [3]:
N = int(input('введите число: ')) # задаю N
list_ = [] # создаю пустой список для заполнения

while N >= 0: 
  list_.append(N) # в цикле от N до 0 наполняю список
  N -= 1

list_r = np.array(list_) # превращаю список в массив numpy
list_r
# получается массив, который начинается именно с N.

введите число: 6


array([6, 5, 4, 3, 2, 1, 0])

#### Вариант 2. по "напримеру" (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
N = int(input('Введите число: ')) # задаю N

list_ = np.arange(0, N)  # в библиотеке numpy нашел метод, создающий массив

res = np.flipud(list_)  # в библиотеке numpy нашел метод, инвертирующий порядок элементов массива 

res
# получается массив, который начинается c N-1

Введите число: 8


array([7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2. Диагональная матрица. Сумма значений диагонали.

In [7]:
# использую для решения массив из предыдущей задачи, вариант 2 (res).
# все методы - и создание матрицы, и расчет суммы - нашел в библиотеке numpy. 

m_diag = np.diag(res)

m_diag_sum = np.sum(res)

print('Диагональная матрица: ')
print() # пустая строчка (для красоты и чтобы "каши" не было)
print(m_diag)
print()
print('Сумма значений диагонали: ', m_diag_sum)

Диагональная матрица: 

[[7 0 0 0 0 0 0 0]
 [0 6 0 0 0 0 0 0]
 [0 0 5 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 3 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]]

Сумма значений диагонали:  28


### Задание 3. Решение системы уравнений

In [9]:
"""
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
"""
# записываю в массивы коэффициенты к переменным. Если переменной нет - значит, коэфф=0.
# Задача - получить матрицу - то есть в каждом списке массива д.б. одинаковое кол-во элементов:

M = np.array([[4., 2., 1.], [1., 3., 0.], [0., 5., 4.]]) # Матрица (левая часть системы уравнений)

# записываю в массив значения уравнений (левая часть) - получается вектор:
v = np.array([4., 12., -3.]) # Вектор (правая часть системы уравнений)

a = np.linalg.solve(M, v) # решаю уравнение с помощью numpy

print(a) # получили список значений переменных

# представляю решение уравнений в привычном виде
# т.е. показываю, чему равна каждая переменная:

l = list(a)
res_x = format(l[0], '.3f') # округляю до тысячных
res_y = format(l[1], '.3f')
res_z = format(l[2], '.3f')
print('x = ', res_x)
print('y = ', res_y)
print('z = ', res_z)


[ 0.46666667  3.84444444 -5.55555556]
x =  0.467
y =  3.844
z =  -5.556


P.S. Проверил решение на калькуляторе - сошлось.

### Задание 4. Из занятия.

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array:

In [10]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [11]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

Решение:

In [13]:
# Повторю данные задачи:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

# Решение:

cosine = [] # Создаю пустой список
i = 0 # создаю счетчик

print('Косинусное сходство нового пользователя с каждым пользователем из базы:') # "шапка" для вывода результата (для красоты)

# используя материалы занятия считаю косинусы, но делаю это в цикле, проходясь по всем спискам - элементам массива-матрицы:
for item in users_stats:
  aLength = np.linalg.norm( users_stats[i] )
  bLength = np.linalg.norm( next_user_stats )  

  cos_ = np.dot( users_stats[i], next_user_stats) / ( aLength * bLength )
  cosine.append(cos_)
 
  print(cos_)
  i = i+1

# определяю максимальное значение косинуса из полученных
max_ = max(cosine)
print(max(cosine))

# определяю ID клиента с максимальным значением косинуса:
closer_user_ID = cosine.index(max_) + 1

print()# пропускаю строчку (для красоты)
print('Самый похожий пользователь: User_ID: ',closer_user_ID)

Косинусное сходство нового пользователя с каждым пользователем из базы:
0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
0.9486832980505138

Самый похожий пользователь: User_ID:  8
